runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest
- name: MySQLdb
  version: latest

# [START handlers]
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
# [END handlers]

beta_settings:
  cloud_sql_instances: lookingbus5:us-west2:sql-instance-5
